name = "XKBlas"
uuid = "8d3f9e88-0651-4e8b-8f79-7d9d5f5f9e88"
authors = ["Michel <michel@example.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
CEnum = "0.5.0"
CUDA = "5.9.3"
KernelAbstractions = "0.9.39"
Libdl = "1.11.0"
Scratch = "1.3.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
