[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CMake_jll = "3f4e10e2-61f2-5801-8945-23b9d642d0e6"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
