[compat]
LLVM_full_jll = "20"
julia = "1.10"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CMake_jll = "3f4e10e2-61f2-5801-8945-23b9d642d0e6"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
LLVM_full_jll = "a3ccf953-465e-511d-b87f-60a6490c289d"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Ninja_jll = "76642167-d241-5cee-8c94-7a494e8cb7b7"
OpenBLAS_jll = "4536629a-c528-5b80-bd46-f80d51c5b363"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
